"""
An enormous factorial
For any prime p the number N(p,q) is defined by N(p,q) = ∑n=0 to q Tn*pn
with Tn generated by the following random number generator:

S0 = 290797
Sn+1 = Sn^2 mod 50515093
Tn = Sn mod p

Let Nfac(p,q) be the factorial of N(p,q).
Let NF(p,q) be the number of factors p in Nfac(p,q).

You are given that $NF(3,10000) \mod 3^{20}=624955285$.

Find $NF(61,10^7) \mod 61^{10}$
"""

from itertools import islice

from digits import undigits
from mod_arith import modinv


def rng():
    s = 290797
    while True:
        yield s
        s = s*s % 50515093

p, q = 61, 10**7
modulo_power = 10
modulo = p**modulo_power

# Since we know the digits of n, and since the modulo is a power of p,
# we can calculate the p-adic valuation of n! without fully calculating
# n!, by using Legendre's formula.
n_digs = [s % p for s in islice(rng(), q+1)]
n_mod_modulo = undigits(n_digs[:modulo_power][::-1], p)
result = (n_mod_modulo - sum(n_digs)) * modinv(modulo, p-1) % modulo

print(result)
correct_answer = "605857431263981935"