"""
Triangular, pentagonal, and hexagonal
Triangle, pentagonal, and hexagonal numbers are generated by the 
following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n-1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n-1) 	  	    1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from itertools import count

from sequences import intersection


def triangular_numbers():
    return (k * (k + 1) // 2 for k in count(1))
def pentagonal_numbers():
    return (k * (3*k - 1) // 2 for k in count(1))
def hexagonal_numbers():
    return (k * (2*k - 1) for k in count(1))

for n in intersection(triangular_numbers(), pentagonal_numbers(), hexagonal_numbers()):
    if n > 40755:
        result = n
        break

print(result)
correct_answer = "1533776805"