"""
Highly divisible triangular number
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The 
first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

import factorization
from arithfunct import sigma_nat
from primes import primes_lt

prime_limit = 10**6 # guestimate...
factorization.generate_default_primes_and_hints(prime_limit)

def divisor_count(n):
    return sigma_nat(n, a=0)

triangle_number = 0
for i in range(1, prime_limit):
    triangle_number += i
    if divisor_count(triangle_number) > 500:
        break  # Found the answer!
else:
    raise Exception("Probably need more primes")

print(triangle_number)
correct_answer = "76576500"